# -*- coding: utf-8 -*-
"""AI-DS-JOB-SALARY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FuFrEuDHuTxCC71Sgyfj917popDUPgHV
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['figure.figsize'] = (8,5)
sns.set_style('whitegrid')
sns.set_theme()
df = pd.read_csv('ai_ds_job_salaries_2026.csv', delimiter=';')
for col in df.columns:
    df_null = df[col].isnull().sum()
    df_null_pct = df_null / len(df)*100
    print(col, df_null, df_null_pct)

df.dtypes

df.head(5)

import matplotlib.ticker as mticker

top_level_salary = df.groupby(['job_title', 'experience_level','company_location']).agg({'salary_usd':'mean'}).sort_values(ascending=False, by='salary_usd').head(10)
sns.barplot(data=top_level_salary.reset_index(), x='job_title', y='salary_usd', hue='company_location')
plt.xlabel('Job Title')
plt.xticks(rotation=45)
plt.ylabel('Average Salary')
plt.title('Top 10 Job Titles By Highest Salaries')

# Format y-axis labels to K with $ sign
def dollar_formatter(x, pos):
    return f'${int(x/1000)}K'

formatter = mticker.FuncFormatter(dollar_formatter)
plt.gca().yaxis.set_major_formatter(formatter)

plt.tight_layout()
plt.show()

df_emp = df['employment_type'].value_counts().sort_values(ascending=False)
df_emp

plt.pie(df_emp.values, labels=df_emp.index, autopct='%1.1f%%')
plt.title("Employment Type")
plt.show()

import numpy as np
import pandas.api.types as pdt

for col in df.columns:
  if pdt.is_numeric_dtype(df[col]) and not pdt.is_bool_dtype(df[col]):
    plt.hist(df[col], bins=20)
    plt.xlabel(col)
    plt.title(f"Distribution of {col}")
    plt.show()

numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object', 'bool']).columns.tolist()

if 'salary_usd' in numerical_cols:
    numerical_cols.remove('salary_usd')

print(f"Numerical columns: {numerical_cols}")
print(f"Categorical columns: {categorical_cols}")

X = pd.get_dummies(df[categorical_cols], drop_first=True)
X = pd.concat([X, df[numerical_cols]], axis=1)
y = df['salary_usd']

print(f"Shape of features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")
print("First 5 rows of X:")
print(X.head())
print("First 5 rows of y:")
print(y.head())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

print(f"Model training complete. Trained on {X_train.shape[0]} samples, tested on {X_test.shape[0]} samples.")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


y_pred = model.predict(X_test)


mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2) Score: {r2:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns


plot_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Actual', y='Predicted', data=plot_df, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], '--r', label='Perfect Prediction')
plt.title('Actual vs. Predicted Salary (USD)')
plt.xlabel('Actual Salary (USD)')
plt.ylabel('Predicted Salary (USD)')
plt.legend()
plt.show()

residuals = y_test - y_pred
plt.figure(figsize=(10, 6))
sns.histplot(residuals, kde=True)
plt.title('Distribution of Residuals')
plt.xlabel('Residuals (Actual - Predicted)')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Get feature importances from the model
feature_importances = model.feature_importances_

feature_names = X_train.columns

importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importances
})

importance_df = importance_df.sort_values(by='Importance', ascending=False)

plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=importance_df.head(20))
plt.title('Top 20 Feature Importances for Salary Prediction')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()