# -*- coding: utf-8 -*-
"""DATA-ANALYSIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcAQgFh0V2IlnyJcWpwCdR8_a-mQ9qDO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Sklearn (Preprocessing & Missing values)
from sklearn.impute import KNNImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

# Sklearn (Supervised & Unsupervised Models)
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.semi_supervised import LabelSpreading
from sklearn.metrics import mean_squared_error, r2_score, silhouette_score

# ReportLab (PDF)
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet

# =====================================================================
# 1. MODULE : LOADER
# =====================================================================
def load_csv(file_path: str) -> pd.DataFrame:
    """Charge un fichier CSV de manière sécurisée."""
    try:
        df = pd.read_csv(file_path)
        print(f"✅ Données chargées avec succès : {df.shape} lignes, {df.shape[1]} colonnes.")
        return df
    except Exception as e:
        print(f"❌ Erreur lors du chargement : {e}")
        raise

# =====================================================================
# 2. MODULE : CLEANER
# =====================================================================
def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    """Nettoie le DataFrame de base (suppression des doublons)."""
    df_cleaned = df.drop_duplicates()
    return df_cleaned

def knn_impute_missing(df: pd.DataFrame, n_neighbors: int = 5) -> pd.DataFrame:
    """Impute les valeurs manquantes des colonnes numériques via KNNImputer."""
    df_imputed = df.copy()
    num_cols = df_imputed.select_dtypes(include=['number']).columns

    if len(num_cols) > 0 and df_imputed[num_cols].isnull().any().any():
        imputer = KNNImputer(n_neighbors=n_neighbors)
        df_imputed[num_cols] = imputer.fit_transform(df_imputed[num_cols])
        print(f"🔹 Imputation KNN complétée ({n_neighbors} voisins) sur les colonnes numériques.")
    return df_imputed

def handle_outliers(df: pd.DataFrame, columns: list) -> pd.DataFrame:
    """Cap les valeurs aberrantes via la méthode de l'écart interquartile (IQR)."""
    df_out = df.copy()
    for col in columns:
        if col in df_out.columns and pd.api.types.is_numeric_dtype(df_out[col]):
            Q1 = df_out[col].quantile(0.25)
            Q3 = df_out[col].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            df_out[col] = df_out[col].clip(lower=lower_bound, upper=upper_bound)
    print(f"🔹 Valeurs aberrantes traitées pour : {columns}")
    return df_out

def encode_categorical(df: pd.DataFrame, categorical_cols: list) -> pd.DataFrame:
    """Encode les variables textuelles/catégorielles en valeurs numériques (One-Hot)."""
    df_encoded = df.copy()
    valid_cols = [c for c in categorical_cols if c in df_encoded.columns]

    if valid_cols:
        encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
        encoded_data = encoder.fit_transform(df_encoded[valid_cols])
        encoded_cols = encoder.get_feature_names_out(valid_cols)

        df_encoded_meta = pd.DataFrame(encoded_data, columns=encoded_cols, index=df_encoded.index)
        df_encoded = pd.concat([df_encoded.drop(columns=valid_cols), df_encoded_meta], axis=1)
        print(f"🔹 Colonnes catégorielles encodées : {valid_cols}")
    return df_encoded

def feature_scaling(df: pd.DataFrame, columns: list) -> pd.DataFrame:
    """Normalise les colonnes numériques (Min-Max Scaling entre 0 et 1)."""
    df_scaled = df.copy()
    for col in columns:
        if col in df_scaled.columns:
            min_val = df_scaled[col].min()
            max_val = df_scaled[col].max()
            if max_val != min_val:
                df_scaled[col] = (df_scaled[col] - min_val) / (max_val - min_val)
    print(f"🔹 Normalisation min-max appliquée sur : {columns}")
    return df_scaled

# =====================================================================
# 3. MODULE : ANALYZER
# =====================================================================
def get_statistics(df: pd.DataFrame) -> pd.DataFrame:
    """Calcule les statistiques descriptives de base."""
    return df.describe()

def plot_distribution(df: pd.DataFrame, column: str, output_path: str):
    """Génère et sauvegarde l'histogramme d'une colonne."""
    plt.figure(figsize=(6, 4))
    df[column].hist(bins=20, color='skyblue', edgecolor='black')
    plt.title(f"Distribution de {column}")
    plt.savefig(output_path, bbox_inches='tight')
    plt.close()

def plot_scatterplot(df: pd.DataFrame, x_col: str, y_col: str, output_path: str):
    """Génère un graphique de dispersion (Scatter Plot)."""
    plt.figure(figsize=(6, 4))
    sns.scatterplot(data=df, x=x_col, y=y_col, color='purple')
    plt.title(f"Nuage de points : {y_col} vs {x_col}")
    plt.savefig(output_path, bbox_inches='tight')
    plt.close()

def plot_boxplot(df: pd.DataFrame, column: str, output_path: str):
    """Génère une boîte à moustaches (Box Plot) pour visualiser les écarts."""
    plt.figure(figsize=(6, 4))
    sns.boxplot(data=df, y=column, color='lightgreen')
    plt.title(f"Boîte à moustaches de {column}")
    plt.savefig(output_path, bbox_inches='tight')
    plt.close()

def plot_pie_plot(df: pd.DataFrame, column: str, output_path: str):
    """Génère un diagramme circulaire (Pie Plot) pour une variable catégorielle."""
    plt.figure(figsize=(6, 4))
    df[column].value_counts().plot.pie(autopct='%1.1f%%', cmap='pastel1', startangle=90)
    plt.ylabel('')
    plt.title(f"Proportions de {column}")
    plt.savefig(output_path, bbox_inches='tight')
    plt.close()

def plot_correlation_heatmap(df: pd.DataFrame, output_path: str):
    """Génère une carte de chaleur (Heatmap) de la matrice de corrélation."""
    plt.figure(figsize=(8, 6))
    num_df = df.select_dtypes(include=['number'])
    if not num_df.empty:
        corr = num_df.corr()
        sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
        plt.title("Matrice de corrélation")
        plt.savefig(output_path, bbox_inches='tight')
    plt.close()

# =====================================================================
# 4. MODULE : MODELER
# =====================================================================
def train_predictive_model(df: pd.DataFrame, target_col: str, feature_cols: list) -> dict:
    """Supervisé : Entraîne un modèle Random Forest (Régression)."""
    X = df[feature_cols]
    y = df[target_col]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestRegressor(random_state=42)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    rmse = mean_squared_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)
    print(f"🤖 [Supervisé] Modèle entraîné. R²: {r2:.2f} | RMSE: {rmse:.2f}")
    return {"type": "Supervisé", "r2": f"{r2:.2f}", "rmse": f"{rmse:.2f}"}

def train_unsupervised_model(df: pd.DataFrame, feature_cols: list, n_clusters: int = 3) -> dict:
    """Non Supervisé : Effectue un clustering K-Means et calcule le score de Silhouette."""
    X = df[feature_cols]

    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init='auto')
    cluster_labels = kmeans.fit_transform(X) # ou .fit_predict(X)
    labels = kmeans.labels_

    # Calcul de la métrique si le nombre de lignes le permet
    score = silhouette_score(X, labels) if len(X) > n_clusters else 0.0
    print(f"🤖 [Non Supervisé] K-Means complété. Clusters: {n_clusters} | Silhouette: {score:.2f}")
    return {"type": "Non Supervisé", "clusters": str(n_clusters), "silhouette": f"{score:.2f}"}

def train_semi_supervised_model(df: pd.DataFrame, target_col: str, feature_cols: list) -> dict:
    """Semi-Supervisé : Applique LabelSpreading. Les valeurs manquantes de la cible doivent être marquées à -1."""
    X = df[feature_cols]
    y = df[target_col].copy()

    # Simulation/Sécurisation : s'il n'y a pas de données non étiquetées (-1), on force 20% des labels à -1
    if not (y == -1).any():
        rng = np.random.default_rng(42)
        random_unlabeled_points = rng.random(y.shape) < 0.2
        y[random_unlabeled_points] = -1

    model = LabelSpreading(kernel='knn', n_neighbors=5)
    model.fit(X, y)
    print("🤖 [Semi-Supervisé] LabelSpreading ajusté avec succès.")
    return {"type": "Semi-Supervisé", "statut": "Modèle ajusté"}

def run_reinforcement_learning_simulation(steps: int = 100) -> dict:
    """Reinforcement Learning : Simulation rapide d'un algorithme Q-Learning (Multi-Armed Bandit)."""
    # 3 actions possibles, l'action 2 donne la meilleure récompense
    q_table = np.zeros(3)
    alpha = 0.1  # Taux d'apprentissage
    gamma = 0.9  # Facteur d'atténuation
    epsilon = 0.1

    rng = np.random.default_rng(42)
    total_reward = 0
    for _ in range(steps):
        if rng.random() < epsilon:
            action = rng.choice(3)
        else:
            action = np.argmax(q_table)

        # Récompenses simulées (la vraie action optimale est 2)
        reward = rng.normal(loc=10.0 if action == 2 else 2.0, scale=1.0)
        total_reward += reward

        # Mise à jour simplifiée de la Q-Table (Bandit manchot)
        q_table[action] += alpha * (reward - q_table[action])

    print(f"🤖 [Reinforcement] Simulation complétée. Récompense totale cumulée : {total_reward:.2f}")
    return {"type": "Reinforcement Learning", "total_reward": f"{total_reward:.2f}", "best_action_q_value": f"{q_table[2]:.2f}"}

# =====================================================================
# 5. MODULE : REPORTER
# =====================================================================
# 5. MODULE : REPORTER (Mis en forme professionnellement)
# =====================================================================
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_pdf_report(output_path: str, metrics: list, charts: list):
    """Génère un rapport d'analyse unifié complet et structuré graphiquement."""
    # Configuration du document avec des marges standards (2 cm)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=54, leftMargin=54,
        topMargin=54, bottomMargin=54
    )
    story = []

    # Configuration des styles personnalisés
    base_styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=base_styles['Title'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#1A365D"),  # Bleu marine corporatif
        alignment=0,  # Aligné à gauche
        spaceAfter=15
    )

    h1_style = ParagraphStyle(
        'SectionH1',
        parent=base_styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#2B6CB0"),  # Bleu secondaire
        spaceBefore=18,
        spaceAfter=10,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=base_styles['BodyText'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#2D3748")  # Gris foncé lisible
    )

    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=body_style,
        fontName='Helvetica-Bold',
        textColor=colors.white
    )

    # 1. En-tête et Titre principal
    story.append(Paragraph("Rapport d'Analyse Avancé Multimodèle", title_style))
    story.append(Paragraph("Généré automatiquement par le pipeline d'analyse modulaire.", body_style))
    story.append(Spacer(1, 15))

    # Ligne de séparation colorée
    sep_table = Table([[""]], colWidths=[504], rowHeights=[2])
    sep_table.setStyle(TableStyle([('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#2B6CB0"))]))
    story.append(sep_table)
    story.append(Spacer(1, 15))

    # 2. Section Métriques d'apprentissage (Sous forme de Tableau)
    story.append(Paragraph("1. Métriques de Performance des Modèles", h1_style))
    story.append(Paragraph("Le tableau ci-dessous récapitule les scores obtenus pour chaque type d'apprentissage exécuté :", body_style))
    story.append(Spacer(1, 10))

    # Construction des lignes du tableau de bord
    table_data = [[Paragraph("Type de Modèle", table_header_style), Paragraph("Détails et Métriques Associées", table_header_style)]]
    for m in metrics:
        model_type = m.get('type', 'Inconnu')
        # Formatage propre des dictionnaires de métriques en chaînes lisibles
        details_str = ", ".join([f"<b>{k}</b>: {v}" for k, v in m.items() if k != 'type'])
        table_data.append([
            Paragraph(f"<b>{model_type}</b>", body_style),
            Paragraph(details_str, body_style)
        ])

    # Application d'un style de tableau épuré et professionnel
    metrics_table = Table(table_data, colWidths=[130, 374])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1A365D")),  # En-tête bleu marine
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor("#F7FAFC"), colors.white]), # Alternance gris/blanc
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),  # Bordures fines grises
        ('TOPPADDING', (0, 1), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 20))

    # 3. Section Visualisations graphiques (Mise en page Grid/Côte à côte)
    story.append(Paragraph("2. Visualisations Graphiques Exploratoires", h1_style))
    story.append(Spacer(1, 5))

    # Organisation des graphiques deux par deux pour maximiser l'espace
    grid_data = []
    current_row = []

    for chart in charts:
        try:
            img = Image(chart, width=240, height=170)
            current_row.append(img)
        except Exception:
            current_row.append(Paragraph(f"<i>Image manquante : {chart}</i>", body_style))

        if len(current_row) == 2:
            grid_data.append(current_row)
            current_row = []

    if current_row:
        current_row.append("")  # Cellule vide si nombre impair d'images
        grid_data.append(current_row)

    if grid_data:
        chart_table = Table(grid_data, colWidths=[252, 252])
        chart_table.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ]))
        story.append(chart_table)

    # Génération finale du livrable
    doc.build(story)
    print(f"📄 Rapport PDF professionnel généré avec succès : {output_path}")
