# -*- coding: utf-8 -*-
"""Copy of Meteo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tb1OIgCX0UQiky-1EXALmlWvWfK7qxBz
"""

import requests
def retrieve_meteo(city, api_key):
  url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric&lang=fr"
  try:
    response = requests.get(url)
    response.raise_for_status()
    return response.json()
  except requests.exceptions.RequestException as e:
    print(f"Erreur lors de la requête à l'API: {e}")
    return None

def display_meteo(data):
  if not data:
    print("Aucune donnée à afficher")
    return
  city_name = data.get("name")
  country   = data.get("sys", {}).get("country")
  temp      = data.get("main", {}).get("temp")
  desc_list = data.get("weather", [{}])
  desc = desc_list[0].get("description") if desc_list else None
  humidity  = data.get("main", {}).get("humidity")
  wind_speed= data.get("wind", {}).get("speed")
  print(f"Météo pour {city_name}, {country}")
  print(f"Température : {temp} °C")
  print(f"Condition: {desc.capitalize()}")
  print(f"Humidité: {humidity}")

API="44cd622236748a0b1b4638c7e36fa10c"
def main():
  city_name = input("Entrez le nom de la ville: ")
  print("Recherche des données en cours...")
  data_ = retrieve_meteo(city_name, API)
  print("Données récupérées avec succès !")
  display_meteo(data_)
if __name__=="__main__":
  main()